//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cita
    {
        public int IdCita { get; set; }
        public Nullable<int> IdUsuario { get; set; }
        public Nullable<int> IdEspecialista { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<System.TimeSpan> Horario { get; set; }
        public Nullable<int> Estatus { get; set; }
    
        public virtual Especialista Especialista { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
