//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Especialista
    {
        public int IdEspecialista { get; set; }
        public string NombreCarrera { get; set; }
        public string NoCedula { get; set; }
        public string Especialidad { get; set; }
        public string Calle { get; set; }
        public string NumeroExterno { get; set; }
        public string NumeroInterno { get; set; }
        public string Ciudad { get; set; }
        public string Estado { get; set; }
        public string CodigoPostal { get; set; }
        public string Telefono { get; set; }
        public Nullable<bool> Estatus { get; set; }
        public Nullable<int> IdUsuario { get; set; }
        public string Colonia { get; set; }
        public string Celular { get; set; }
    
        public virtual Usuario Usuario { get; set; }
    }
}
