//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Like
    {
        public int IdLike { get; set; }
        public Nullable<int> IdUsuario { get; set; }
        public Nullable<int> IdMultimedia { get; set; }
        public Nullable<bool> IsLike { get; set; }
    
        public virtual Multimedia Multimedia { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
