//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Like
    {
        public int IdLike { get; set; }
        public Nullable<int> IdUsuario { get; set; }
        public Nullable<int> IdMultimedia { get; set; }
        public Nullable<bool> IsLike { get; set; }
    
        public virtual Multimedia Multimedia { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
